networks:
  dev:
    driver: bridge

services:
  postgres:
    image: postgres:16
#    volumes:
#      - $PWD/docker/postgres-init:/docker-entrypoint-initdb.d:cached
#      - $PWD/work/postgres:/var/lib/postgresql/data:cached
    environment:
      POSTGRES_PASSWORD: postgres
    networks:
      - dev
    ports:
      - 5432:5432

  buildapp:
    image: buildedapp
    networks:
      - dev
    hostname: localhost
    ports:
      - 8080:8080