name: build

on:
  push:
    branches: 
    - "*"

jobs:
  build:
    runs-on: self-hosted
      
    steps:
      - uses: actions/checkout@v4

      - name: run app
        run: |
          cd ./code/backend
          sudo docker compose up -d --build
